const WORDS_DATA = {
  "3_1": {
    title: "三年级 Unit 1",
    desc: "情绪与感受类单词 · 27个",
    words: [
      { word: "feeling", spell: "f-e-e-l-i-n-g", phonetic: "/ˈfiːlɪŋ/", cn: "感觉" },
      { word: "tired", spell: "t-i-r-e-d", phonetic: "/ˈtaɪəd/", cn: "疲惫的" },
      { word: "sad", spell: "s-a-d", phonetic: "/sæd/", cn: "难过的" },
      { word: "angry", spell: "a-n-g-r-y", phonetic: "/ˈæŋɡri/", cn: "生气的" },
      { word: "scared", spell: "s-c-a-r-e-d", phonetic: "/skeəd/", cn: "害怕的" },
      { word: "cry", spell: "c-r-y", phonetic: "/kraɪ/", cn: "哭" },
      { word: "laugh", spell: "l-a-u-g-h", phonetic: "/lɑːf/", cn: "笑" },
      { word: "stamp", spell: "s-t-a-m-p", phonetic: "/stæmp/", cn: "跺（脚）" },
      { word: "sleep", spell: "s-l-e-e-p", phonetic: "/sliːp/", cn: "睡觉" },
      { word: "new", spell: "n-e-w", phonetic: "/njuː/", cn: "新的" },
      { word: "game", spell: "g-a-m-e", phonetic: "/ɡeɪm/", cn: "游戏" },
      { word: "excited", spell: "e-x-c-i-t-e-d", phonetic: "/ɪkˈsaɪtɪd/", cn: "兴奋的" },
      { word: "sorry", spell: "s-o-r-r-y", phonetic: "/ˈsɒri/", cn: "对不起" },
      { word: "like", spell: "l-i-k-e", phonetic: "/laɪk/", cn: "喜欢" },
      { word: "but", spell: "b-u-t", phonetic: "/bʌt/", cn: "但是" },
      { word: "unhappy", spell: "u-n-h-a-p-p-y", phonetic: "/ʌnˈhæpi/", cn: "不开心的" },
      { word: "worried", spell: "w-o-r-r-i-e-d", phonetic: "/ˈwʌrid/", cn: "担心的" },
      { word: "not", spell: "n-o-t", phonetic: "/nɒt/", cn: "不，不是" },
      { word: "feel", spell: "f-e-e-l", phonetic: "/fiːl/", cn: "感觉到，觉得" },
      { word: "find", spell: "f-i-n-d", phonetic: "/faɪnd/", cn: "找到" },
      { word: "doll", spell: "d-o-l-l", phonetic: "/dɒl/", cn: "玩偶" },
      { word: "football", spell: "f-o-o-t-b-a-l-l", phonetic: "/ˈfʊtbɔːl/", cn: "足球" },
      { word: "eat", spell: "e-a-t", phonetic: "/iːt/", cn: "吃" },
      { word: "his", spell: "h-i-s", phonetic: "/hɪz/", cn: "他的" },
      { word: "cake", spell: "c-a-k-e", phonetic: "/keɪk/", cn: "蛋糕" },
      { word: "big", spell: "b-i-g", phonetic: "/bɪɡ/", cn: "大的" },
      { word: "mouse", spell: "m-o-u-s-e", phonetic: "/maʊs/", cn: "老鼠" }
    ]
  },

  "3_2": {
    title: "三年级 Unit 2",
    desc: "身体部位与动作类 共30个",
    words: [
      { word: "know", spell: "k-n-o-w", phonetic: "/noʊ/", cn: "了解" },
      { word: "body", spell: "b-o-d-y", phonetic: "/ˈbɑːdi/", cn: "身体；躯干" },
      { word: "rock", spell: "r-o-c-k", phonetic: "/rɒk/", cn: "摇滚乐" },
      { word: "song", spell: "s-o-n-g", phonetic: "/sɒŋ/", cn: "歌曲" },
      { word: "touch", spell: "t-o-u-c-h", phonetic: "/tʌtʃ/", cn: "触摸" },
      { word: "head", spell: "h-e-a-d", phonetic: "/hed/", cn: "头" },
      { word: "eye", spell: "e-y-e", phonetic: "/aɪ/", cn: "眼睛" },
      { word: "hair", spell: "h-a-i-r", phonetic: "/heə/", cn: "头发" },
      { word: "ear", spell: "e-a-r", phonetic: "/ɪə/", cn: "耳朵" },
      { word: "wave", spell: "w-a-v-e", phonetic: "/weɪv/", cn: "摆动" },
      { word: "leg", spell: "l-e-g", phonetic: "/leɡ/", cn: "腿" },
      { word: "foot", spell: "f-o-o-t", phonetic: "/fʊt/", cn: "脚" },
      { word: "nose", spell: "n-o-s-e", phonetic: "/nəʊz/", cn: "鼻子" },
      { word: "face", spell: "f-a-c-e", phonetic: "/feɪs/", cn: "脸" },
      { word: "arm", spell: "a-r-m", phonetic: "/ɑːm/", cn: "手臂" },
      { word: "hand", spell: "h-a-n-d", phonetic: "/hænd/", cn: "手" },
      { word: "mouth", spell: "m-o-u-t-h", phonetic: "/maʊθ/", cn: "嘴" },
      { word: "tooth", spell: "t-o-o-t-h", phonetic: "/tuːθ/", cn: "牙" },
      { word: "prize", spell: "p-r-i-z-e", phonetic: "/praɪz/", cn: "奖品" },
      { word: "bike", spell: "b-i-k-e", phonetic: "/baɪk/", cn: "自行车" },
      { word: "race", spell: "r-a-c-e", phonetic: "/reɪs/", cn: "竞赛" },
      { word: "stretch", spell: "s-t-r-e-t-c-h", phonetic: "/stretʃ/", cn: "伸展" },
      { word: "shake", spell: "s-h-a-k-e", phonetic: "/ʃeɪk/", cn: "摇动" },
      { word: "here", spell: "h-e-r-e", phonetic: "/hɪə/", cn: "在这里" },
      { word: "Mr", spell: "M-r", phonetic: "/ˈmɪstə/", cn: "先生" },
      { word: "back", spell: "b-a-c-k", phonetic: "/bæk/", cn: "回到原处" },
      { word: "worry", spell: "w-o-r-r-y", phonetic: "/ˈwʌri/", cn: "担心" },
      { word: "short", spell: "s-h-o-r-t", phonetic: "/ʃɔːt/", cn: "短的" },
      { word: "small", spell: "s-m-a-l-l", phonetic: "/smɔːl/", cn: "小的" },
      { word: "robot", spell: "r-o-b-o-t", phonetic: "/ˈrəʊbɒt/", cn: "机器人" }
    ]
  },

  "3_3": {
    title: "三年级 Unit 3",
    desc: "服装 40个",
    words: [
      { word: "so", spell: "s-o", phonetic: "/səʊ/", cn: "这么，如此" },
      { word: "cool", spell: "c-o-o-l", phonetic: "/kuːl/", cn: "酷的" },
      { word: "clothes", spell: "c-l-o-t-h-e-s", phonetic: "/kləʊðz/", cn: "衣服" },
      { word: "wear", spell: "w-e-a-r", phonetic: "/weə/", cn: "穿" },
      { word: "cap", spell: "c-a-p", phonetic: "/kæp/", cn: "（有帽舌的）帽子" },
      { word: "T-shirt", spell: "T-s-h-i-r-t", phonetic: "/ˈtiːʃɜːt/", cn: "T恤" },
      { word: "trousers", spell: "t-r-o-u-s-e-r-s", phonetic: "/ˈtraʊzəz/", cn: "裤子" },
      { word: "sock", spell: "s-o-c-k", phonetic: "/sɒk/", cn: "袜子" },
      { word: "shiny", spell: "s-h-i-n-y", phonetic: "/ˈʃaɪni/", cn: "有光泽的" },
      { word: "shoe", spell: "s-h-o-e", phonetic: "/ʃuː/", cn: "鞋" },
      { word: "dress", spell: "d-r-e-s-s", phonetic: "/dres/", cn: "连衣裙" },
      { word: "sweater", spell: "s-w-e-a-t-e-r", phonetic: "/ˈswetə/", cn: "毛线衣" },
      { word: "skirt", spell: "s-k-i-r-t", phonetic: "/skɜːt/", cn: "半身裙" },
      { word: "shirt", spell: "s-h-i-r-t", phonetic: "/ʃɜːt/", cn: "衬衫" },
      { word: "coat", spell: "c-o-a-t", phonetic: "/kəʊt/", cn: "外套" },
      { word: "shorts", spell: "s-h-o-r-t-s", phonetic: "/ʃɔːts/", cn: "短裤" },
      { word: "king", spell: "k-i-n-g", phonetic: "/kɪŋ/", cn: "国王" },
      { word: "want", spell: "w-a-n-t", phonetic: "/wɒnt/", cn: "想要" },
      { word: "beautiful", spell: "b-e-a-u-t-i-f-u-l", phonetic: "/ˈbjuːtɪfl/", cn: "美丽的" },
      { word: "make", spell: "m-a-k-e", phonetic: "/meɪk/", cn: "做" },
      { word: "magic", spell: "m-a-g-i-c", phonetic: "/ˈmædʒɪk/", cn: "神奇的" },
      { word: "people", spell: "p-e-o-p-l-e", phonetic: "/ˈpiːpl/", cn: "人" },
      { word: "them", spell: "t-h-e-m", phonetic: "/ðem/", cn: "它们" },
      { word: "after", spell: "a-f-t-e-r", phonetic: "/ˈɑːftə/", cn: "在……后" },
      { word: "month", spell: "m-o-n-t-h", phonetic: "/mʌnθ/", cn: "一个月；月" },
      { word: "try", spell: "t-r-y", phonetic: "/traɪ/", cn: "试" },
      { word: "try sth on", spell: "t-r-y s-t-h o-n", phonetic: "/traɪ sʌm ɒn/", cn: "试穿" },
      { word: "why", spell: "w-h-y", phonetic: "/waɪ/", cn: "为什么" },
      { word: "wonderful", spell: "w-o-n-d-e-r-f-u-l", phonetic: "/ˈwʌndəfl/", cn: "令人惊叹的" },
      { word: "most", spell: "m-o-s-t", phonetic: "/məʊst/", cn: "最" },
      { word: "any", spell: "a-n-y", phonetic: "/ˈeni/", cn: "任何的" },
      { word: "or", spell: "o-r", phonetic: "/ɔː/", cn: "或" },
      { word: "fox", spell: "f-o-x", phonetic: "/fɒks/", cn: "狐狸" },
      { word: "monkey", spell: "m-o-n-k-e-y", phonetic: "/ˈmʌŋki/", cn: "猴子" },
      { word: "tell", spell: "t-e-l-l", phonetic: "/tel/", cn: "告诉；说出" },
      { word: "truth", spell: "t-r-u-t-h", phonetic: "/truːθ/", cn: "真相" },
      { word: "wash", spell: "w-a-s-h", phonetic: "/wɒʃ/", cn: "洗" },
      { word: "hang", spell: "h-a-n-g", phonetic: "/hæŋ/", cn: "悬挂" },
      { word: "hat", spell: "h-a-t", phonetic: "/hæt/", cn: "帽子" },
      { word: "jeans", spell: "j-e-a-n-s", phonetic: "/dʒiːnz/", cn: "牛仔裤" },
      { word: "boot", spell: "b-o-o-t", phonetic: "/buːt/", cn: "靴子" },
      { word: "robe", spell: "r-o-b-e", phonetic: "/rəʊb/", cn: "长袍" }
    ]
  },

  "3_4": {
    title: "三年级 Unit 4",
    desc: "天气 42个",
    words: [
      { word: "weather", spell: "w-e-a-t-h-e-r", phonetic: "/ˈweðə/", cn: "天气" },
      { word: "bookshop", spell: "b-o-o-k-s-h-o-p", phonetic: "/ˈbʊkʃɒp/", cn: "书店" },
      { word: "rain", spell: "r-a-i-n", phonetic: "/reɪn/", cn: "雨" },
      { word: "sun", spell: "s-u-n", phonetic: "/sʌn/", cn: "阳光" },
      { word: "wait", spell: "w-a-i-t", phonetic: "/weɪt/", cn: "等" },
      { word: "wet", spell: "w-e-t", phonetic: "/wet/", cn: "湿的" },
      { word: "rainy", spell: "r-a-i-n-y", phonetic: "/ˈreɪni/", cn: "多雨的" },
      { word: "again", spell: "a-g-a-i-n", phonetic: "/əˈɡeɪn/", cn: "又" },
      { word: "run", spell: "r-u-n", phonetic: "/rʌn/", cn: "跑" },
      { word: "dry", spell: "d-r-y", phonetic: "/draɪ/", cn: "干燥的" },
      { word: "windy", spell: "w-i-n-d-y", phonetic: "/ˈwɪndi/", cn: "多风的" },
      { word: "sell", spell: "s-e-l-l", phonetic: "/sel/", cn: "卖" },
      { word: "fly", spell: "f-l-y", phonetic: "/flaɪ/", cn: "放飞" },
      { word: "these", spell: "t-h-e-s-e", phonetic: "/ðiːz/", cn: "this的复数形式" },
      { word: "kite", spell: "k-i-t-e", phonetic: "/kaɪt/", cn: "风筝" },
      { word: "idea", spell: "i-d-e-a", phonetic: "/aɪˈdɪə/", cn: "主意" },
      { word: "park", spell: "p-a-r-k", phonetic: "/pɑːk/", cn: "公园" },
      { word: "club", spell: "c-l-u-b", phonetic: "/klʌb/", cn: "俱乐部" },
      { word: "hot", spell: "h-o-t", phonetic: "/hɒt/", cn: "炎热的" },
      { word: "welcome", spell: "w-e-l-c-o-m-e", phonetic: "/ˈwelkəm/", cn: "欢迎" },
      { word: "sunny", spell: "s-u-n-n-y", phonetic: "/ˈsʌni/", cn: "阳光充足的" },
      { word: "stand", spell: "s-t-a-n-d", phonetic: "/stænd/", cn: "站立" },
      { word: "swim", spell: "s-w-i-m", phonetic: "/swɪm/", cn: "游泳" },
      { word: "board", spell: "b-o-a-r-d", phonetic: "/bɔːd/", cn: "公告牌" },
      { word: "water", spell: "w-a-t-e-r", phonetic: "/ˈwɔːtə/", cn: "水" },
      { word: "walk", spell: "w-a-l-k", phonetic: "/wɔːk/", cn: "走" },
      { word: "cold", spell: "c-o-l-d", phonetic: "/kəʊld/", cn: "寒冷的" },
      { word: "carefully", spell: "c-a-r-e-f-u-l-l-y", phonetic: "/ˈkeəfəli/", cn: "小心地" },
      { word: "snowy", spell: "s-n-o-w-y", phonetic: "/ˈsnəʊi/", cn: "多雪的" },
      { word: "tree", spell: "t-r-e-e", phonetic: "/triː/", cn: "树" },
      { word: "throw", spell: "t-h-r-o-w", phonetic: "/θrəʊ/", cn: "投，扔" },
      { word: "spring", spell: "s-p-r-i-n-g", phonetic: "/sprɪŋ/", cn: "春天" },
      { word: "snowball", spell: "s-n-o-w-b-a-l-l", phonetic: "/ˈsnəʊbɔːl/", cn: "雪球" },
      { word: "summer", spell: "s-u-m-m-e-r", phonetic: "/ˈsʌmə/", cn: "夏天" },
      { word: "umbrella", spell: "u-m-b-r-e-l-l-a", phonetic: "/ʌmˈbrelə/", cn: "雨伞" },
      { word: "autumn", spell: "a-u-t-u-m-n", phonetic: "/ˈɔːtəm/", cn: "秋天" },
      { word: "warm", spell: "w-a-r-m", phonetic: "/wɔːm/", cn: "保暖的" },
      { word: "music", spell: "m-u-s-i-c", phonetic: "/ˈmjuːzɪk/", cn: "音乐" },
      { word: "winter", spell: "w-i-n-t-e-r", phonetic: "/ˈwɪntə/", cn: "冬天" },
      { word: "season", spell: "s-e-a-s-o-n", phonetic: "/ˈsiːzn/", cn: "季节" },
      { word: "drawing", spell: "d-r-a-w-i-n-g", phonetic: "/ˈdrɔːɪŋ/", cn: "图画" },
      { word: "cloudy", spell: "c-l-o-u-d-y", phonetic: "/ˈklaʊdi/", cn: "多云的" }
    ]
  },

  "3_5": {
    title: "三年级 Unit 5",
    desc: "星期与活动 26个",
    words: [
      { word: "week", spell: "w-e-e-k", phonetic: "/wiːk/", cn: "星期" },
      { word: "Monday", spell: "M-o-n-d-a-y", phonetic: "/ˈmʌndeɪ/", cn: "星期一" },
      { word: "Tuesday", spell: "T-u-e-s-d-a-y", phonetic: "/ˈtjuːzdeɪ/", cn: "星期二" },
      { word: "Wednesday", spell: "W-e-d-n-e-s-d-a-y", phonetic: "/ˈwenzdeɪ/", cn: "星期三" },
      { word: "Thursday", spell: "T-h-u-r-s-d-a-y", phonetic: "/ˈθɜːzdeɪ/", cn: "星期四" },
      { word: "Friday", spell: "F-r-i-d-a-y", phonetic: "/ˈfraɪdeɪ/", cn: "星期五" },
      { word: "Saturday", spell: "S-a-t-u-r-d-a-y", phonetic: "/ˈsætədeɪ/", cn: "星期六" },
      { word: "Sunday", spell: "S-u-n-d-a-y", phonetic: "/ˈsʌndeɪ/", cn: "星期日" },
      { word: "before", spell: "b-e-f-o-r-e", phonetic: "/bɪˈfɔː/", cn: "在……以前" },
      { word: "room", spell: "r-o-o-m", phonetic: "/ruːm/", cn: "房间" },
      { word: "close", spell: "c-l-o-s-e", phonetic: "/kləʊs/", cn: "关，闭合" },
      { word: "much", spell: "m-u-c-h", phonetic: "/mʌtʃ/", cn: "非常" },
      { word: "of course", spell: "o-f c-o-u-r-s-e", phonetic: "/ɒv kɔːs/", cn: "当然" },
      { word: "rabbit", spell: "r-a-b-b-i-t", phonetic: "/ˈræbɪt/", cn: "兔" },
      { word: "cat", spell: "c-a-t", phonetic: "/kæt/", cn: "猫" },
      { word: "fish", spell: "f-i-s-h", phonetic: "/fɪʃ/", cn: "鱼" },
      { word: "busy", spell: "b-u-s-y", phonetic: "/ˈbɪzi/", cn: "忙碌的" },
      { word: "every", spell: "e-v-e-r-y", phonetic: "/ˈevri/", cn: "每一个" },
      { word: "cooking", spell: "c-o-o-k-i-n-g", phonetic: "/ˈkʊkɪŋ/", cn: "做饭" },
      { word: "cook", spell: "c-o-o-k", phonetic: "/kʊk/", cn: "烹调" },
      { word: "Chinese", spell: "C-h-i-n-e-s-e", phonetic: "/ˌtʃaɪˈniːz/", cn: "中国的" },
      { word: "chess", spell: "c-h-e-s-s", phonetic: "/tʃes/", cn: "国际象棋" },
      { word: "Chinese chess", spell: "C-h-i-n-e-s-e c-h-e-s-s", phonetic: "/ˌtʃaɪˈniːz tʃes/", cn: "中国象棋" },
      { word: "study", spell: "s-t-u-d-y", phonetic: "/ˈstʌdi/", cn: "学习" },
      { word: "basketball", spell: "b-a-s-k-e-t-b-a-l-l", phonetic: "/ˈbɑːskɪtbɔːl/", cn: "篮球" },
      { word: "activity", spell: "a-c-t-i-v-i-t-y", phonetic: "/ækˈtɪvəti/", cn: "活动" }
    ]
  },

  "3_6": {
    title: "三年级 Unit 6",
    desc: "食物 32个",
    words: [
      { word: "bread", spell: "b-r-e-a-d", phonetic: "/bred/", cn: "面包" },
      { word: "milk", spell: "m-i-l-k", phonetic: "/mɪlk/", cn: "奶" },
      { word: "rice", spell: "r-i-c-e", phonetic: "/raɪs/", cn: "米；米饭" },
      { word: "tomato", spell: "t-o-m-a-t-o", phonetic: "/təˈmɑːtəʊ/", cn: "西红柿" },
      { word: "juice", spell: "j-u-i-c-e", phonetic: "/dʒuːs/", cn: "果汁" },
      { word: "candy", spell: "c-a-n-d-y", phonetic: "/ˈkændi/", cn: "糖果" },
      { word: "ice", spell: "i-c-e", phonetic: "/aɪs/", cn: "冰" },
      { word: "cream", spell: "c-r-e-a-m", phonetic: "/kriːm/", cn: "奶油" },
      { word: "ice cream", spell: "i-c-e c-r-e-a-m", phonetic: "/aɪs kriːm/", cn: "冰激凌" },
      { word: "chicken", spell: "c-h-i-c-k-e-n", phonetic: "/ˈtʃɪkɪn/", cn: "鸡肉" },
      { word: "noodles", spell: "n-o-o-d-l-e-s", phonetic: "/ˈnuːdlz/", cn: "（一般用复数）面条" },
      { word: "banana", spell: "b-a-n-a-n-a", phonetic: "/bəˈnɑːnə/", cn: "香蕉" },
      { word: "dinner", spell: "d-i-n-n-e-r", phonetic: "/ˈdɪnə/", cn: "正餐" },
      { word: "parent", spell: "p-a-r-e-n-t", phonetic: "/ˈpeərənt/", cn: "父，母" },
      { word: "dish", spell: "d-i-s-h", phonetic: "/dɪʃ/", cn: "一道菜" },
      { word: "meat", spell: "m-e-a-t", phonetic: "/miːt/", cn: "肉" },
      { word: "mushroom", spell: "m-u-s-h-r-o-o-m", phonetic: "/ˈmʌʃruːm/", cn: "蘑菇" },
      { word: "potato", spell: "p-o-t-a-t-o", phonetic: "/pəˈteɪtəʊ/", cn: "土豆" },
      { word: "eggplant", spell: "e-g-g-p-l-a-n-t", phonetic: "/ˈeɡplɑːnt/", cn: "茄子" },
      { word: "food", spell: "f-o-o-d", phonetic: "/fuːd/", cn: "食物" },
      { word: "amazing", spell: "a-m-a-z-i-n-g", phonetic: "/əˈmeɪzɪŋ/", cn: "惊人的" },
      { word: "say", spell: "s-a-y", phonetic: "/seɪ/", cn: "说" },
      { word: "grape", spell: "g-r-a-p-e", phonetic: "/ɡreɪp/", cn: "葡萄" },
      { word: "vegetable", spell: "v-e-g-e-t-a-b-l-e", phonetic: "/ˈvedʒtəbl/", cn: "蔬菜" },
      { word: "soup", spell: "s-o-u-p", phonetic: "/suːp/", cn: "汤" },
      { word: "drink", spell: "d-r-i-n-k", phonetic: "/drɪŋk/", cn: "饮料" },
      { word: "need", spell: "n-e-e-d", phonetic: "/niːd/", cn: "需要" },
      { word: "oil", spell: "o-i-l", phonetic: "/ɔɪl/", cn: "植物油，动物油" },
      { word: "salt", spell: "s-a-l-t", phonetic: "/sɔːlt/", cn: "盐" },
      { word: "beat", spell: "b-e-a-t", phonetic: "/biːt/", cn: "搅拌，搅打" },
      { word: "apple", spell: "a-p-p-l-e", phonetic: "/ˈæpl/", cn: "苹果" },
      { word: "egg", spell: "e-g-g", phonetic: "/eɡ/", cn: "鸡蛋" }
    ]
  },

  "cet4_1": {
    title: "CET4 Unit 1",
    desc: "",
    words: [
      { word: "access", spell: "a-c-c-e-s-s", phonetic: "/ˈækses/", cn: " 获取  接近，入口" },
      { word: "project", spell: "p-r-o-j-e-c-t", phonetic: "/ˈprɒdʒekt/", cn: " 工程；课题、作业" },
      { word: "intention", spell: "i-n-t-e-n-t-i-o-n", phonetic: "/ɪnˈtenʃən/", cn: " 打算，意图" },
      { word: "equivalence", spell: "e-q-u-i-v-a-l-e-n-c-e", phonetic: "/ɪˈkwɪvələns/", cn: " 等值，相等" },
      { word: "negotiate", spell: "n-e-g-o-t-i-a-t-e", phonetic: "/nɪˈɡəʊʃieɪt/", cn: " 谈判，协商，交涉" },
      { word: "disappointing", spell: "d-i-s-a-p-p-o-i-n-t-i-n-g", phonetic: "/ˌdɪsəˈpɔɪntɪŋ/", cn: " 令人失望的" },
      { word: "alternative", spell: "a-l-t-e-r-n-a-t-i-v-e", phonetic: "/ɔːlˈtɜːnətɪv/", cn: " 代替品" },
      { word: "generous", spell: "g-e-n-e-r-o-u-s", phonetic: "/ˈdʒenərəs/", cn: " 慷慨的" },
      { word: "biological", spell: "b-i-o-l-o-g-i-c-a-l", phonetic: "/ˌbaɪəˈlɒdʒɪkl/", cn: " 生物的" },
      { word: "strategy", spell: "s-t-r-a-t-e-g-y", phonetic: "/ˈstrætədʒi/", cn: " 策略，战略" },
      { word: "paradox", spell: "p-a-r-a-d-o-x", phonetic: "/ˈpærədɒks/", cn: " 悖论；自相矛盾" },
      { word: "primary", spell: "p-r-i-m-a-r-y", phonetic: "/ˈpraɪməri/", cn: " 主要的，基本的" },
      { word: "standpoint", spell: "s-t-a-n-d-p-o-i-n-t", phonetic: "/ˈstændpɔɪnt/", cn: " 立场" },
      { word: "grab", spell: "g-r-a-b", phonetic: "/ɡræb/", cn: " 抢先，抢占，抢夺" },
      { word: "crucial", spell: "c-r-u-c-i-a-l", phonetic: "/ˈkruːʃl/", cn: " 至关重要的" },
      { word: "flaw", spell: "f-l-a-w", phonetic: "/flɔː/", cn: " 缺点；错误" },
      { word: "depressed", spell: "d-e-p-r-e-s-s-e-d", phonetic: "/dɪˈprest/", cn: " 萧条的；沮丧的" },
      { word: "obstacle", spell: "o-b-s-t-a-c-l-e", phonetic: "/ˈɒbstəkl/", cn: " 阻碍" },
      { word: "automatic", spell: "a-u-t-o-m-a-t-i-c", phonetic: "/ˌɔːtəˈmætɪk/", cn: " 自动的" },
      { word: "passionate", spell: "p-a-s-s-i-o-n-a-t-e", phonetic: "/ˈpæʃənət/", cn: " 热情的" },
      { word: "gambling", spell: "g-a-m-b-l-i-n-g", phonetic: "/ˈɡæmblɪŋ/", cn: " 赌博" },
      { word: "logic", spell: "l-o-g-i-c", phonetic: "/ˈlɒdʒɪk/", cn: " 逻辑" },
      { word: "theory", spell: "t-h-e-o-r-y", phonetic: "/ˈθɪəri/", cn: " 理论" },
      { word: "download", spell: "d-o-w-n-l-o-a-d", phonetic: "/ˈdaʊnləʊd/", cn: " 下载" },
      { word: "signal", spell: "s-i-g-n-a-l", phonetic: "/ˈsɪɡnl/", cn: " 信号  发信号，打信号；示意" },
      { word: "authoritative", spell: "a-u-t-h-o-r-i-t-a-t-i-v-e", phonetic: "/ɔːˈθɒrətətɪv/", cn: " 权威的" },
      { word: "smooth", spell: "s-m-o-o-t-h", phonetic: "/smuːð/", cn: " 光滑的" },
      { word: "institution", spell: "i-n-s-t-i-t-u-t-i-o-n", phonetic: "/ˌɪnstɪˈtjuːʃn/", cn: " 社会公共机构；制度；设立，制定" },
      { word: "vehicle", spell: "v-e-h-i-c-l-e", phonetic: "/ˈviːɪkl/", cn: " 车辆" },
      { word: "plague", spell: "p-l-a-g-e", phonetic: "/pleɪɡ/", cn: " 使困扰" },
      { word: "psychological", spell: "p-s-y-c-h-o-l-o-g-i-c-a-l", phonetic: "/ˌsaɪkəˈlɒdʒɪkl/", cn: " 心理上的" },
      { word: "shade", spell: "s-h-a-d-e", phonetic: "/ʃeɪd/", cn: " 阴凉处" },
      { word: "persistent", spell: "p-e-r-s-i-s-t-e-n-t", phonetic: "/pəˈsɪstənt/", cn: " 持续的；坚持的" },
      { word: "voluntary", spell: "v-o-l-u-n-t-a-r-y", phonetic: "/ˈvɒləntri/", cn: " 自愿的，主动的" },
      { word: "tolerance", spell: "t-o-l-e-r-a-n-c-e", phonetic: "/ˈtɒlərəns/", cn: " 宽容，容忍" },
      { word: "senior", spell: "s-e-n-i-o-r", phonetic: "/ˈsiːniə/", cn: " 老年人" },
      { word: "individual", spell: "i-n-d-i-v-i-d-u-a-l", phonetic: "/ˌɪndɪˈvɪdʒuəl/", cn: " 个人" },
      { word: "contemporary", spell: "c-o-n-t-e-m-p-o-r-a-r-y", phonetic: "/kənˈtempərəri/", cn: " 当代的，现代的" },
      { word: "opposite", spell: "o-p-p-o-s-i-t-e", phonetic: "/ˈɒpəzɪt/", cn: " 相反的" },
      { word: "specialize", spell: "s-p-e-c-i-a-l-i-z-e", phonetic: "/ˈspeʃəlaɪz/", cn: " 专业从事" },
      { word: "content", spell: "c-o-n-t-e-n-t", phonetic: "/ˈkɒntent/", cn: " 内容" },
      { word: "philosopher", spell: "p-h-i-l-o-s-o-p-h-e-r", phonetic: "/fɪˈlɒsəfə/", cn: " 哲学家" },
      { word: "unrest", spell: "u-n-r-e-s-t", phonetic: "/ʌnˈrest/", cn: " 不安定，动荡" },
      { word: "startle", spell: "s-t-a-r-t-l-e", phonetic: "/ˈstɑːtl/", cn: " 吃惊" },
      { word: "emission", spell: "e-m-i-s-s-i-o-n", phonetic: "/ɪˈmɪʃn/", cn: " 排放，辐射" },
      { word: "overweight", spell: "o-v-e-r-w-e-i-g-h-t", phonetic: "/ˌəʊvəˈweɪt/", cn: " 超重的" },
      { word: "occupation", spell: "o-c-c-u-p-a-t-i-o-n", phonetic: "/ˌɒkjuˈpeɪʃn/", cn: " 职业，工作" },
      { word: "mainstream", spell: "m-a-i-n-s-t-r-e-a-m", phonetic: "/ˈmeɪnstriːm/", cn: " 主流" },
      { word: "scholarship", spell: "s-c-h-o-l-a-r-s-h-i-p", phonetic: "/ˈskɒləʃɪp/", cn: " 奖学金" },
      { word: "contract", spell: "c-o-n-t-r-a-c-t", phonetic: "/ˈkɒntrækt/", cn: " 合同" }
    ]
  }
};
