const WORDS_DATA = {
  "3_1": {
    title: "三年级 Unit 1",
    desc: "情绪与感受类单词 · 27个",
    words: [
      { word: "feeling", spell: "f-e-e-l-i-n-g", phonetic: "/ˈfiːlɪŋ/", cn: "感觉" },
      { word: "tired", spell: "t-i-r-e-d", phonetic: "/ˈtaɪəd/", cn: "疲惫的" },
      { word: "sad", spell: "s-a-d", phonetic: "/sæd/", cn: "难过的" },
      { word: "angry", spell: "a-n-g-r-y", phonetic: "/ˈæŋɡri/", cn: "生气的" },
      { word: "scared", spell: "s-c-a-r-e-d", phonetic: "/skeəd/", cn: "害怕的" },
      { word: "cry", spell: "c-r-y", phonetic: "/kraɪ/", cn: "哭" },
      { word: "laugh", spell: "l-a-u-g-h", phonetic: "/lɑːf/", cn: "笑" },
      { word: "stamp", spell: "s-t-a-m-p", phonetic: "/stæmp/", cn: "跺（脚）" },
      { word: "sleep", spell: "s-l-e-e-p", phonetic: "/sliːp/", cn: "睡觉" },
      { word: "new", spell: "n-e-w", phonetic: "/njuː/", cn: "新的" },
      { word: "game", spell: "g-a-m-e", phonetic: "/ɡeɪm/", cn: "游戏" },
      { word: "excited", spell: "e-x-c-i-t-e-d", phonetic: "/ɪkˈsaɪtɪd/", cn: "兴奋的" },
      { word: "sorry", spell: "s-o-r-r-y", phonetic: "/ˈsɒri/", cn: "对不起" },
      { word: "like", spell: "l-i-k-e", phonetic: "/laɪk/", cn: "喜欢" },
      { word: "but", spell: "b-u-t", phonetic: "/bʌt/", cn: "但是" },
      { word: "unhappy", spell: "u-n-h-a-p-p-y", phonetic: "/ʌnˈhæpi/", cn: "不开心的" },
      { word: "worried", spell: "w-o-r-r-i-e-d", phonetic: "/ˈwʌrid/", cn: "担心的" },
      { word: "not", spell: "n-o-t", phonetic: "/nɒt/", cn: "不，不是" },
      { word: "feel", spell: "f-e-e-l", phonetic: "/fiːl/", cn: "感觉到，觉得" },
      { word: "find", spell: "f-i-n-d", phonetic: "/faɪnd/", cn: "找到" },
      { word: "doll", spell: "d-o-l-l", phonetic: "/dɒl/", cn: "玩偶" },
      { word: "football", spell: "f-o-o-t-b-a-l-l", phonetic: "/ˈfʊtbɔːl/", cn: "足球" },
      { word: "eat", spell: "e-a-t", phonetic: "/iːt/", cn: "吃" },
      { word: "his", spell: "h-i-s", phonetic: "/hɪz/", cn: "他的" },
      { word: "cake", spell: "c-a-k-e", phonetic: "/keɪk/", cn: "蛋糕" },
      { word: "big", spell: "b-i-g", phonetic: "/bɪɡ/", cn: "大的" },
      { word: "mouse", spell: "m-o-u-s-e", phonetic: "/maʊs/", cn: "老鼠" }
    ]
  },

  "3_2": {
    title: "三年级 Unit 2",
    desc: "身体部位与动作类 共30个",
    words: [
      { word: "know", spell: "k-n-o-w", phonetic: "/noʊ/", cn: "了解" },
      { word: "body", spell: "b-o-d-y", phonetic: "/ˈbɑːdi/", cn: "身体；躯干" },
      { word: "rock", spell: "r-o-c-k", phonetic: "/rɒk/", cn: "摇滚乐" },
      { word: "song", spell: "s-o-n-g", phonetic: "/sɒŋ/", cn: "歌曲" },
      { word: "touch", spell: "t-o-u-c-h", phonetic: "/tʌtʃ/", cn: "触摸" },
      { word: "head", spell: "h-e-a-d", phonetic: "/hed/", cn: "头" },
      { word: "eye", spell: "e-y-e", phonetic: "/aɪ/", cn: "眼睛" },
      { word: "hair", spell: "h-a-i-r", phonetic: "/heə/", cn: "头发" },
      { word: "ear", spell: "e-a-r", phonetic: "/ɪə/", cn: "耳朵" },
      { word: "wave", spell: "w-a-v-e", phonetic: "/weɪv/", cn: "摆动" },
      { word: "leg", spell: "l-e-g", phonetic: "/leɡ/", cn: "腿" },
      { word: "foot", spell: "f-o-o-t", phonetic: "/fʊt/", cn: "脚" },
      { word: "nose", spell: "n-o-s-e", phonetic: "/nəʊz/", cn: "鼻子" },
      { word: "face", spell: "f-a-c-e", phonetic: "/feɪs/", cn: "脸" },
      { word: "arm", spell: "a-r-m", phonetic: "/ɑːm/", cn: "手臂" },
      { word: "hand", spell: "h-a-n-d", phonetic: "/hænd/", cn: "手" },
      { word: "mouth", spell: "m-o-u-t-h", phonetic: "/maʊθ/", cn: "嘴" },
      { word: "tooth", spell: "t-o-o-t-h", phonetic: "/tuːθ/", cn: "牙" },
      { word: "prize", spell: "p-r-i-z-e", phonetic: "/praɪz/", cn: "奖品" },
      { word: "bike", spell: "b-i-k-e", phonetic: "/baɪk/", cn: "自行车" },
      { word: "race", spell: "r-a-c-e", phonetic: "/reɪs/", cn: "竞赛" },
      { word: "stretch", spell: "s-t-r-e-t-c-h", phonetic: "/stretʃ/", cn: "伸展" },
      { word: "shake", spell: "s-h-a-k-e", phonetic: "/ʃeɪk/", cn: "摇动" },
      { word: "here", spell: "h-e-r-e", phonetic: "/hɪə/", cn: "在这里" },
      { word: "Mr", spell: "M-r", phonetic: "/ˈmɪstə/", cn: "先生" },
      { word: "back", spell: "b-a-c-k", phonetic: "/bæk/", cn: "回到原处" },
      { word: "worry", spell: "w-o-r-r-y", phonetic: "/ˈwʌri/", cn: "担心" },
      { word: "short", spell: "s-h-o-r-t", phonetic: "/ʃɔːt/", cn: "短的" },
      { word: "small", spell: "s-m-a-l-l", phonetic: "/smɔːl/", cn: "小的" },
      { word: "robot", spell: "r-o-b-o-t", phonetic: "/ˈrəʊbɒt/", cn: "机器人" }
    ]
  },

  "3_3": {
    title: "三年级 Unit 3",
    desc: "服装 40个",
    words: [
      { word: "so", spell: "s-o", phonetic: "/səʊ/", cn: "这么，如此" },
      { word: "cool", spell: "c-o-o-l", phonetic: "/kuːl/", cn: "酷的" },
      { word: "clothes", spell: "c-l-o-t-h-e-s", phonetic: "/kləʊðz/", cn: "衣服" },
      { word: "wear", spell: "w-e-a-r", phonetic: "/weə/", cn: "穿" },
      { word: "cap", spell: "c-a-p", phonetic: "/kæp/", cn: "（有帽舌的）帽子" },
      { word: "T-shirt", spell: "T-s-h-i-r-t", phonetic: "/ˈtiːʃɜːt/", cn: "T恤" },
      { word: "trousers", spell: "t-r-o-u-s-e-r-s", phonetic: "/ˈtraʊzəz/", cn: "裤子" },
      { word: "sock", spell: "s-o-c-k", phonetic: "/sɒk/", cn: "袜子" },
      { word: "shiny", spell: "s-h-i-n-y", phonetic: "/ˈʃaɪni/", cn: "有光泽的" },
      { word: "shoe", spell: "s-h-o-e", phonetic: "/ʃuː/", cn: "鞋" },
      { word: "dress", spell: "d-r-e-s-s", phonetic: "/dres/", cn: "连衣裙" },
      { word: "sweater", spell: "s-w-e-a-t-e-r", phonetic: "/ˈswetə/", cn: "毛线衣" },
      { word: "skirt", spell: "s-k-i-r-t", phonetic: "/skɜːt/", cn: "半身裙" },
      { word: "shirt", spell: "s-h-i-r-t", phonetic: "/ʃɜːt/", cn: "衬衫" },
      { word: "coat", spell: "c-o-a-t", phonetic: "/kəʊt/", cn: "外套" },
      { word: "shorts", spell: "s-h-o-r-t-s", phonetic: "/ʃɔːts/", cn: "短裤" },
      { word: "king", spell: "k-i-n-g", phonetic: "/kɪŋ/", cn: "国王" },
      { word: "want", spell: "w-a-n-t", phonetic: "/wɒnt/", cn: "想要" },
      { word: "beautiful", spell: "b-e-a-u-t-i-f-u-l", phonetic: "/ˈbjuːtɪfl/", cn: "美丽的" },
      { word: "make", spell: "m-a-k-e", phonetic: "/meɪk/", cn: "做" },
      { word: "magic", spell: "m-a-g-i-c", phonetic: "/ˈmædʒɪk/", cn: "神奇的" },
      { word: "people", spell: "p-e-o-p-l-e", phonetic: "/ˈpiːpl/", cn: "人" },
      { word: "them", spell: "t-h-e-m", phonetic: "/ðem/", cn: "它们" },
      { word: "after", spell: "a-f-t-e-r", phonetic: "/ˈɑːftə/", cn: "在……后" },
      { word: "month", spell: "m-o-n-t-h", phonetic: "/mʌnθ/", cn: "一个月；月" },
      { word: "try", spell: "t-r-y", phonetic: "/traɪ/", cn: "试" },
      { word: "try sth on", spell: "t-r-y s-t-h o-n", phonetic: "/traɪ sʌm ɒn/", cn: "试穿" },
      { word: "why", spell: "w-h-y", phonetic: "/waɪ/", cn: "为什么" },
      { word: "wonderful", spell: "w-o-n-d-e-r-f-u-l", phonetic: "/ˈwʌndəfl/", cn: "令人惊叹的" },
      { word: "most", spell: "m-o-s-t", phonetic: "/məʊst/", cn: "最" },
      { word: "any", spell: "a-n-y", phonetic: "/ˈeni/", cn: "任何的" },
      { word: "or", spell: "o-r", phonetic: "/ɔː/", cn: "或" },
      { word: "fox", spell: "f-o-x", phonetic: "/fɒks/", cn: "狐狸" },
      { word: "monkey", spell: "m-o-n-k-e-y", phonetic: "/ˈmʌŋki/", cn: "猴子" },
      { word: "tell", spell: "t-e-l-l", phonetic: "/tel/", cn: "告诉；说出" },
      { word: "truth", spell: "t-r-u-t-h", phonetic: "/truːθ/", cn: "真相" },
      { word: "wash", spell: "w-a-s-h", phonetic: "/wɒʃ/", cn: "洗" },
      { word: "hang", spell: "h-a-n-g", phonetic: "/hæŋ/", cn: "悬挂" },
      { word: "hat", spell: "h-a-t", phonetic: "/hæt/", cn: "帽子" },
      { word: "jeans", spell: "j-e-a-n-s", phonetic: "/dʒiːnz/", cn: "牛仔裤" },
      { word: "boot", spell: "b-o-o-t", phonetic: "/buːt/", cn: "靴子" },
      { word: "robe", spell: "r-o-b-e", phonetic: "/rəʊb/", cn: "长袍" }
    ]
  },

  "3_4": {
    title: "三年级 Unit 4",
    desc: "天气 42个",
    words: [
      { word: "weather", spell: "w-e-a-t-h-e-r", phonetic: "/ˈweðə/", cn: "天气" },
      { word: "bookshop", spell: "b-o-o-k-s-h-o-p", phonetic: "/ˈbʊkʃɒp/", cn: "书店" },
      { word: "rain", spell: "r-a-i-n", phonetic: "/reɪn/", cn: "雨" },
      { word: "sun", spell: "s-u-n", phonetic: "/sʌn/", cn: "阳光" },
      { word: "wait", spell: "w-a-i-t", phonetic: "/weɪt/", cn: "等" },
      { word: "wet", spell: "w-e-t", phonetic: "/wet/", cn: "湿的" },
      { word: "rainy", spell: "r-a-i-n-y", phonetic: "/ˈreɪni/", cn: "多雨的" },
      { word: "again", spell: "a-g-a-i-n", phonetic: "/əˈɡeɪn/", cn: "又" },
      { word: "run", spell: "r-u-n", phonetic: "/rʌn/", cn: "跑" },
      { word: "dry", spell: "d-r-y", phonetic: "/draɪ/", cn: "干燥的" },
      { word: "windy", spell: "w-i-n-d-y", phonetic: "/ˈwɪndi/", cn: "多风的" },
      { word: "sell", spell: "s-e-l-l", phonetic: "/sel/", cn: "卖" },
      { word: "fly", spell: "f-l-y", phonetic: "/flaɪ/", cn: "放飞" },
      { word: "these", spell: "t-h-e-s-e", phonetic: "/ðiːz/", cn: "this的复数形式" },
      { word: "kite", spell: "k-i-t-e", phonetic: "/kaɪt/", cn: "风筝" },
      { word: "idea", spell: "i-d-e-a", phonetic: "/aɪˈdɪə/", cn: "主意" },
      { word: "park", spell: "p-a-r-k", phonetic: "/pɑːk/", cn: "公园" },
      { word: "club", spell: "c-l-u-b", phonetic: "/klʌb/", cn: "俱乐部" },
      { word: "hot", spell: "h-o-t", phonetic: "/hɒt/", cn: "炎热的" },
      { word: "welcome", spell: "w-e-l-c-o-m-e", phonetic: "/ˈwelkəm/", cn: "欢迎" },
      { word: "sunny", spell: "s-u-n-n-y", phonetic: "/ˈsʌni/", cn: "阳光充足的" },
      { word: "stand", spell: "s-t-a-n-d", phonetic: "/stænd/", cn: "站立" },
      { word: "swim", spell: "s-w-i-m", phonetic: "/swɪm/", cn: "游泳" },
      { word: "board", spell: "b-o-a-r-d", phonetic: "/bɔːd/", cn: "公告牌" },
      { word: "water", spell: "w-a-t-e-r", phonetic: "/ˈwɔːtə/", cn: "水" },
      { word: "walk", spell: "w-a-l-k", phonetic: "/wɔːk/", cn: "走" },
      { word: "cold", spell: "c-o-l-d", phonetic: "/kəʊld/", cn: "寒冷的" },
      { word: "carefully", spell: "c-a-r-e-f-u-l-l-y", phonetic: "/ˈkeəfəli/", cn: "小心地" },
      { word: "snowy", spell: "s-n-o-w-y", phonetic: "/ˈsnəʊi/", cn: "多雪的" },
      { word: "tree", spell: "t-r-e-e", phonetic: "/triː/", cn: "树" },
      { word: "throw", spell: "t-h-r-o-w", phonetic: "/θrəʊ/", cn: "投，扔" },
      { word: "spring", spell: "s-p-r-i-n-g", phonetic: "/sprɪŋ/", cn: "春天" },
      { word: "snowball", spell: "s-n-o-w-b-a-l-l", phonetic: "/ˈsnəʊbɔːl/", cn: "雪球" },
      { word: "summer", spell: "s-u-m-m-e-r", phonetic: "/ˈsʌmə/", cn: "夏天" },
      { word: "umbrella", spell: "u-m-b-r-e-l-l-a", phonetic: "/ʌmˈbrelə/", cn: "雨伞" },
      { word: "autumn", spell: "a-u-t-u-m-n", phonetic: "/ˈɔːtəm/", cn: "秋天" },
      { word: "warm", spell: "w-a-r-m", phonetic: "/wɔːm/", cn: "保暖的" },
      { word: "music", spell: "m-u-s-i-c", phonetic: "/ˈmjuːzɪk/", cn: "音乐" },
      { word: "winter", spell: "w-i-n-t-e-r", phonetic: "/ˈwɪntə/", cn: "冬天" },
      { word: "season", spell: "s-e-a-s-o-n", phonetic: "/ˈsiːzn/", cn: "季节" },
      { word: "drawing", spell: "d-r-a-w-i-n-g", phonetic: "/ˈdrɔːɪŋ/", cn: "图画" },
      { word: "cloudy", spell: "c-l-o-u-d-y", phonetic: "/ˈklaʊdi/", cn: "多云的" }
    ]
  },

  "3_5": {
    title: "三年级 Unit 5",
    desc: "星期与活动 26个",
    words: [
      { word: "week", spell: "w-e-e-k", phonetic: "/wiːk/", cn: "星期" },
      { word: "Monday", spell: "M-o-n-d-a-y", phonetic: "/ˈmʌndeɪ/", cn: "星期一" },
      { word: "Tuesday", spell: "T-u-e-s-d-a-y", phonetic: "/ˈtjuːzdeɪ/", cn: "星期二" },
      { word: "Wednesday", spell: "W-e-d-n-e-s-d-a-y", phonetic: "/ˈwenzdeɪ/", cn: "星期三" },
      { word: "Thursday", spell: "T-h-u-r-s-d-a-y", phonetic: "/ˈθɜːzdeɪ/", cn: "星期四" },
      { word: "Friday", spell: "F-r-i-d-a-y", phonetic: "/ˈfraɪdeɪ/", cn: "星期五" },
      { word: "Saturday", spell: "S-a-t-u-r-d-a-y", phonetic: "/ˈsætədeɪ/", cn: "星期六" },
      { word: "Sunday", spell: "S-u-n-d-a-y", phonetic: "/ˈsʌndeɪ/", cn: "星期日" },
      { word: "before", spell: "b-e-f-o-r-e", phonetic: "/bɪˈfɔː/", cn: "在……以前" },
      { word: "room", spell: "r-o-o-m", phonetic: "/ruːm/", cn: "房间" },
      { word: "close", spell: "c-l-o-s-e", phonetic: "/kləʊs/", cn: "关，闭合" },
      { word: "much", spell: "m-u-c-h", phonetic: "/mʌtʃ/", cn: "非常" },
      { word: "of course", spell: "o-f c-o-u-r-s-e", phonetic: "/ɒv kɔːs/", cn: "当然" },
      { word: "rabbit", spell: "r-a-b-b-i-t", phonetic: "/ˈræbɪt/", cn: "兔" },
      { word: "cat", spell: "c-a-t", phonetic: "/kæt/", cn: "猫" },
      { word: "fish", spell: "f-i-s-h", phonetic: "/fɪʃ/", cn: "鱼" },
      { word: "busy", spell: "b-u-s-y", phonetic: "/ˈbɪzi/", cn: "忙碌的" },
      { word: "every", spell: "e-v-e-r-y", phonetic: "/ˈevri/", cn: "每一个" },
      { word: "cooking", spell: "c-o-o-k-i-n-g", phonetic: "/ˈkʊkɪŋ/", cn: "做饭" },
      { word: "cook", spell: "c-o-o-k", phonetic: "/kʊk/", cn: "烹调" },
      { word: "Chinese", spell: "C-h-i-n-e-s-e", phonetic: "/ˌtʃaɪˈniːz/", cn: "中国的" },
      { word: "chess", spell: "c-h-e-s-s", phonetic: "/tʃes/", cn: "国际象棋" },
      { word: "Chinese chess", spell: "C-h-i-n-e-s-e c-h-e-s-s", phonetic: "/ˌtʃaɪˈniːz tʃes/", cn: "中国象棋" },
      { word: "study", spell: "s-t-u-d-y", phonetic: "/ˈstʌdi/", cn: "学习" },
      { word: "basketball", spell: "b-a-s-k-e-t-b-a-l-l", phonetic: "/ˈbɑːskɪtbɔːl/", cn: "篮球" },
      { word: "activity", spell: "a-c-t-i-v-i-t-y", phonetic: "/ækˈtɪvəti/", cn: "活动" }
    ]
  },

  "3_6": {
    title: "三年级 Unit 6",
    desc: "食物 32个",
    words: [
      { word: "bread", spell: "b-r-e-a-d", phonetic: "/bred/", cn: "面包" },
      { word: "milk", spell: "m-i-l-k", phonetic: "/mɪlk/", cn: "奶" },
      { word: "rice", spell: "r-i-c-e", phonetic: "/raɪs/", cn: "米；米饭" },
      { word: "tomato", spell: "t-o-m-a-t-o", phonetic: "/təˈmɑːtəʊ/", cn: "西红柿" },
      { word: "juice", spell: "j-u-i-c-e", phonetic: "/dʒuːs/", cn: "果汁" },
      { word: "candy", spell: "c-a-n-d-y", phonetic: "/ˈkændi/", cn: "糖果" },
      { word: "ice", spell: "i-c-e", phonetic: "/aɪs/", cn: "冰" },
      { word: "cream", spell: "c-r-e-a-m", phonetic: "/kriːm/", cn: "奶油" },
      { word: "ice cream", spell: "i-c-e c-r-e-a-m", phonetic: "/aɪs kriːm/", cn: "冰激凌" },
      { word: "chicken", spell: "c-h-i-c-k-e-n", phonetic: "/ˈtʃɪkɪn/", cn: "鸡肉" },
      { word: "noodles", spell: "n-o-o-d-l-e-s", phonetic: "/ˈnuːdlz/", cn: "（一般用复数）面条" },
      { word: "banana", spell: "b-a-n-a-n-a", phonetic: "/bəˈnɑːnə/", cn: "香蕉" },
      { word: "dinner", spell: "d-i-n-n-e-r", phonetic: "/ˈdɪnə/", cn: "正餐" },
      { word: "parent", spell: "p-a-r-e-n-t", phonetic: "/ˈpeərənt/", cn: "父，母" },
      { word: "dish", spell: "d-i-s-h", phonetic: "/dɪʃ/", cn: "一道菜" },
      { word: "meat", spell: "m-e-a-t", phonetic: "/miːt/", cn: "肉" },
      { word: "mushroom", spell: "m-u-s-h-r-o-o-m", phonetic: "/ˈmʌʃruːm/", cn: "蘑菇" },
      { word: "potato", spell: "p-o-t-a-t-o", phonetic: "/pəˈteɪtəʊ/", cn: "土豆" },
      { word: "eggplant", spell: "e-g-g-p-l-a-n-t", phonetic: "/ˈeɡplɑːnt/", cn: "茄子" },
      { word: "food", spell: "f-o-o-d", phonetic: "/fuːd/", cn: "食物" },
      { word: "amazing", spell: "a-m-a-z-i-n-g", phonetic: "/əˈmeɪzɪŋ/", cn: "惊人的" },
      { word: "say", spell: "s-a-y", phonetic: "/seɪ/", cn: "说" },
      { word: "grape", spell: "g-r-a-p-e", phonetic: "/ɡreɪp/", cn: "葡萄" },
      { word: "vegetable", spell: "v-e-g-e-t-a-b-l-e", phonetic: "/ˈvedʒtəbl/", cn: "蔬菜" },
      { word: "soup", spell: "s-o-u-p", phonetic: "/suːp/", cn: "汤" },
      { word: "drink", spell: "d-r-i-n-k", phonetic: "/drɪŋk/", cn: "饮料" },
      { word: "need", spell: "n-e-e-d", phonetic: "/niːd/", cn: "需要" },
      { word: "oil", spell: "o-i-l", phonetic: "/ɔɪl/", cn: "植物油，动物油" },
      { word: "salt", spell: "s-a-l-t", phonetic: "/sɔːlt/", cn: "盐" },
      { word: "beat", spell: "b-e-a-t", phonetic: "/biːt/", cn: "搅拌，搅打" },
      { word: "apple", spell: "a-p-p-l-e", phonetic: "/ˈæpl/", cn: "苹果" },
      { word: "egg", spell: "e-g-g", phonetic: "/eɡ/", cn: "鸡蛋" }
    ]
  },

  "cet4_1": {
    title: "CET4 Unit 1",
    desc: "",
    words: [
      { word: "access", spell: "a-c-c-e-s-s", phonetic: "/ˈækses/", cn: " 获取  接近，入口" },
      { word: "project", spell: "p-r-o-j-e-c-t", phonetic: "/ˈprɒdʒekt/", cn: " 工程；课题、作业" },
      { word: "intention", spell: "i-n-t-e-n-t-i-o-n", phonetic: "/ɪnˈtenʃən/", cn: " 打算，意图" },
      { word: "equivalence", spell: "e-q-u-i-v-a-l-e-n-c-e", phonetic: "/ɪˈkwɪvələns/", cn: " 等值，相等" },
      { word: "negotiate", spell: "n-e-g-o-t-i-a-t-e", phonetic: "/nɪˈɡəʊʃieɪt/", cn: " 谈判，协商，交涉" },
      { word: "disappointing", spell: "d-i-s-a-p-p-o-i-n-t-i-n-g", phonetic: "/ˌdɪsəˈpɔɪntɪŋ/", cn: " 令人失望的" },
      { word: "alternative", spell: "a-l-t-e-r-n-a-t-i-v-e", phonetic: "/ɔːlˈtɜːnətɪv/", cn: " 代替品" },
      { word: "generous", spell: "g-e-n-e-r-o-u-s", phonetic: "/ˈdʒenərəs/", cn: " 慷慨的" },
      { word: "biological", spell: "b-i-o-l-o-g-i-c-a-l", phonetic: "/ˌbaɪəˈlɒdʒɪkl/", cn: " 生物的" },
      { word: "strategy", spell: "s-t-r-a-t-e-g-y", phonetic: "/ˈstrætədʒi/", cn: " 策略，战略" },
      { word: "paradox", spell: "p-a-r-a-d-o-x", phonetic: "/ˈpærədɒks/", cn: " 悖论；自相矛盾" },
      { word: "primary", spell: "p-r-i-m-a-r-y", phonetic: "/ˈpraɪməri/", cn: " 主要的，基本的" },
      { word: "standpoint", spell: "s-t-a-n-d-p-o-i-n-t", phonetic: "/ˈstændpɔɪnt/", cn: " 立场" },
      { word: "grab", spell: "g-r-a-b", phonetic: "/ɡræb/", cn: " 抢先，抢占，抢夺" },
      { word: "crucial", spell: "c-r-u-c-i-a-l", phonetic: "/ˈkruːʃl/", cn: " 至关重要的" },
      { word: "flaw", spell: "f-l-a-w", phonetic: "/flɔː/", cn: " 缺点；错误" },
      { word: "depressed", spell: "d-e-p-r-e-s-s-e-d", phonetic: "/dɪˈprest/", cn: " 萧条的；沮丧的" },
      { word: "obstacle", spell: "o-b-s-t-a-c-l-e", phonetic: "/ˈɒbstəkl/", cn: " 阻碍" },
      { word: "automatic", spell: "a-u-t-o-m-a-t-i-c", phonetic: "/ˌɔːtəˈmætɪk/", cn: " 自动的" },
      { word: "passionate", spell: "p-a-s-s-i-o-n-a-t-e", phonetic: "/ˈpæʃənət/", cn: " 热情的" },
      { word: "gambling", spell: "g-a-m-b-l-i-n-g", phonetic: "/ˈɡæmblɪŋ/", cn: " 赌博" },
      { word: "logic", spell: "l-o-g-i-c", phonetic: "/ˈlɒdʒɪk/", cn: " 逻辑" },
      { word: "theory", spell: "t-h-e-o-r-y", phonetic: "/ˈθɪəri/", cn: " 理论" },
      { word: "download", spell: "d-o-w-n-l-o-a-d", phonetic: "/ˈdaʊnləʊd/", cn: " 下载" },
      { word: "signal", spell: "s-i-g-n-a-l", phonetic: "/ˈsɪɡnl/", cn: " 信号  发信号，打信号；示意" },
      { word: "authoritative", spell: "a-u-t-h-o-r-i-t-a-t-i-v-e", phonetic: "/ɔːˈθɒrətətɪv/", cn: " 权威的" },
      { word: "smooth", spell: "s-m-o-o-t-h", phonetic: "/smuːð/", cn: " 光滑的" },
      { word: "institution", spell: "i-n-s-t-i-t-u-t-i-o-n", phonetic: "/ˌɪnstɪˈtjuːʃn/", cn: " 社会公共机构；制度；设立，制定" },
      { word: "vehicle", spell: "v-e-h-i-c-l-e", phonetic: "/ˈviːɪkl/", cn: " 车辆" },
      { word: "plague", spell: "p-l-a-g-e", phonetic: "/pleɪɡ/", cn: " 使困扰" },
      { word: "psychological", spell: "p-s-y-c-h-o-l-o-g-i-c-a-l", phonetic: "/ˌsaɪkəˈlɒdʒɪkl/", cn: " 心理上的" },
      { word: "shade", spell: "s-h-a-d-e", phonetic: "/ʃeɪd/", cn: " 阴凉处" },
      { word: "persistent", spell: "p-e-r-s-i-s-t-e-n-t", phonetic: "/pəˈsɪstənt/", cn: " 持续的；坚持的" },
      { word: "voluntary", spell: "v-o-l-u-n-t-a-r-y", phonetic: "/ˈvɒləntri/", cn: " 自愿的，主动的" },
      { word: "tolerance", spell: "t-o-l-e-r-a-n-c-e", phonetic: "/ˈtɒlərəns/", cn: " 宽容，容忍" },
      { word: "senior", spell: "s-e-n-i-o-r", phonetic: "/ˈsiːniə/", cn: " 老年人" },
      { word: "individual", spell: "i-n-d-i-v-i-d-u-a-l", phonetic: "/ˌɪndɪˈvɪdʒuəl/", cn: " 个人" },
      { word: "contemporary", spell: "c-o-n-t-e-m-p-o-r-a-r-y", phonetic: "/kənˈtempərəri/", cn: " 当代的，现代的" },
      { word: "opposite", spell: "o-p-p-o-s-i-t-e", phonetic: "/ˈɒpəzɪt/", cn: " 相反的" },
      { word: "specialize", spell: "s-p-e-c-i-a-l-i-z-e", phonetic: "/ˈspeʃəlaɪz/", cn: " 专业从事" },
      { word: "content", spell: "c-o-n-t-e-n-t", phonetic: "/ˈkɒntent/", cn: " 内容" },
      { word: "philosopher", spell: "p-h-i-l-o-s-o-p-h-e-r", phonetic: "/fɪˈlɒsəfə/", cn: " 哲学家" },
      { word: "unrest", spell: "u-n-r-e-s-t", phonetic: "/ʌnˈrest/", cn: " 不安定，动荡" },
      { word: "startle", spell: "s-t-a-r-t-l-e", phonetic: "/ˈstɑːtl/", cn: " 吃惊" },
      { word: "emission", spell: "e-m-i-s-s-i-o-n", phonetic: "/ɪˈmɪʃn/", cn: " 排放，辐射" },
      { word: "overweight", spell: "o-v-e-r-w-e-i-g-h-t", phonetic: "/ˌəʊvəˈweɪt/", cn: " 超重的" },
      { word: "occupation", spell: "o-c-c-u-p-a-t-i-o-n", phonetic: "/ˌɒkjuˈpeɪʃn/", cn: " 职业，工作" },
      { word: "mainstream", spell: "m-a-i-n-s-t-r-e-a-m", phonetic: "/ˈmeɪnstriːm/", cn: " 主流" },
      { word: "scholarship", spell: "s-c-h-o-l-a-r-s-h-i-p", phonetic: "/ˈskɒləʃɪp/", cn: " 奖学金" },
      { word: "contract", spell: "c-o-n-t-r-a-c-t", phonetic: "/ˈkɒntrækt/", cn: " 合同" }
    ]
  },

  "cet4_2": {
    title: "CET4 Unit 2",
    desc: "",
    words: [
      { word: "cheek", spell: "c-h-e-e-k", phonetic: "/tʃiːk/", cn: "脸颊" },
      { word: "interdependence", spell: "i-n-t-e-r-d-e-p-e-n-d-e-n-c-e", phonetic: "/ˌɪntədɪˈpendəns/", cn: "相互依靠" },
      { word: "import", spell: "i-m-p-o-r-t", phonetic: "/ˈɪmpɔːt/", cn: "进口" },
      { word: "fiction", spell: "f-i-c-t-i-o-n", phonetic: "/ˈfɪkʃn/", cn: "小说" },
      { word: "upbringing", spell: "u-p-b-r-i-n-g-i-n-g", phonetic: "/ˈʌpbrɪŋɪŋ/", cn: "养育，培养，教养" },
      { word: "preserve", spell: "p-r-e-s-e-r-v-e", phonetic: "/prɪˈzɜːv/", cn: "保护" },
      { word: "vitally", spell: "v-i-t-a-l-l-y", phonetic: "/ˈvaɪtəli/", cn: "极其重要地" },
      { word: "masculine", spell: "m-a-s-c-u-l-i-n-e", phonetic: "/ˈmæskjəlɪn/", cn: "男性的" },
      { word: "advocate", spell: "a-d-v-o-c-a-t-e", phonetic: "/ˈædvəkeɪt/", cn: "倡导" },
      { word: "dust", spell: "d-u-s-t", phonetic: "/dʌst/", cn: "灰尘" },
      { word: "track", spell: "t-r-a-c-k", phonetic: "/træk/", cn: "足迹" },
      { word: "confidence", spell: "c-o-n-f-i-d-e-n-c-e", phonetic: "/ˈkɒnfɪdəns/", cn: "信心" },
      { word: "riotous", spell: "r-i-o-t-o-u-s", phonetic: "/ˈraɪətəs/", cn: "狂暴的" },
      { word: "sophisticated", spell: "s-o-p-h-i-s-t-i-c-a-t-e-d", phonetic: "/səˈfɪstɪkeɪtɪd/", cn: "复杂的；世故的" },
      { word: "similar", spell: "s-i-m-i-l-a-r", phonetic: "/ˈsɪmələ/", cn: "相似的" },
      { word: "transform", spell: "t-r-a-n-s-f-o-r-m", phonetic: "/trænsˈfɔːm/", cn: "改变" },
      { word: "approve", spell: "a-p-p-r-o-v-e", phonetic: "/əˈpruːv/", cn: "赞成，同意" },
      { word: "session", spell: "s-e-s-s-i-o-n", phonetic: "/ˈseʃn/", cn: "开会，会议" },
      { word: "awareness", spell: "a-w-a-r-e-n-e-s-s", phonetic: "/əˈweənəs/", cn: "意识" },
      { word: "exhaust", spell: "e-x-h-a-u-s-t", phonetic: "/ɪɡˈzɔːst/", cn: "使筋疲力尽" },
      { word: "subsidize", spell: "s-u-b-s-i-d-i-z-e", phonetic: "/ˈsʌbsɪdaɪz/", cn: "提供补贴" },
      { word: "grocery", spell: "g-r-o-c-e-r-y", phonetic: "/ˈɡrəʊsəri/", cn: "杂货店" },
      { word: "ignorance", spell: "i-g-n-o-r-a-n-c-e", phonetic: "/ˈɪɡnərəns/", cn: "无知，愚昧" },
      { word: "intelligence", spell: "i-n-t-e-l-l-i-g-e-n-c-e", phonetic: "/ɪnˈtelɪdʒəns/", cn: "智力，智慧，理解力" },
      { word: "tiny", spell: "t-i-n-y", phonetic: "/ˈtaɪni/", cn: "微小的" },
      { word: "praise", spell: "p-r-a-i-s-e", phonetic: "/preɪz/", cn: "赞扬，赞美" },
      { word: "memorize", spell: "m-e-m-o-r-i-z-e", phonetic: "/ˈmeməraɪz/", cn: "熟记，牢记" },
      { word: "relative", spell: "r-e-l-a-t-i-v-e", phonetic: "/ˈrelətɪv/", cn: "相对的" },
      { word: "breakthrough", spell: "b-r-e-a-k-t-h-r-o-u-g-h", phonetic: "/ˈbreɪkθruː/", cn: "突破" },
      { word: "incidence", spell: "i-n-c-i-d-e-n-c-e", phonetic: "/ˈɪnsɪdəns/", cn: "几率，发生率" },
      { word: "scratch", spell: "s-c-r-a-t-c-h", phonetic: "/skrætʃ/", cn: "抓，划痕" },
      { word: "harmful", spell: "h-a-r-m-f-u-l", phonetic: "/ˈhɑːmfəl/", cn: "有害的" },
      { word: "undergo", spell: "u-n-d-e-r-g-o", phonetic: "/ˌʌndəˈɡəʊ/", cn: "承受" },
      { word: "recession", spell: "r-e-c-e-s-s-i-o-n", phonetic: "/rɪˈseʃn/", cn: "衰退" },
      { word: "extraordinary", spell: "e-x-t-r-a-o-r-d-i-n-a-r-y", phonetic: "/ɪkˈstrɔːdənri/", cn: "非凡的" },
      { word: "improper", spell: "i-m-p-r-o-p-e-r", phonetic: "/ɪmˈprɒpə/", cn: "不合适的，不适当的" },
      { word: "marginalize", spell: "m-a-r-g-i-n-a-l-i-z-e", phonetic: "/ˈmɑːdʒɪnəlaɪz/", cn: "边缘化，排斥" },
      { word: "vital", spell: "v-i-t-a-l", phonetic: "/ˈvaɪtl/", cn: "重要的" },
      { word: "fortunately", spell: "f-o-r-t-u-n-a-t-e-l-y", phonetic: "/ˈfɔːtʃənətli/", cn: "幸运地" },
      { word: "commencement", spell: "c-o-m-m-e-n-c-e-m-e-n-t", phonetic: "/kəˈmensmənt/", cn: "毕业典礼" },
      { word: "fetch", spell: "f-e-t-c-h", phonetic: "/fetʃ/", cn: "取回" },
      { word: "clumsy", spell: "c-l-u-m-s-y", phonetic: "/ˈklʌmzi/", cn: "笨拙的，不圆滑的" },
      { word: "establishment", spell: "e-s-t-a-b-l-i-s-h-m-e-n-t", phonetic: "/ɪˈstæblɪʃmənt/", cn: "确立" },
      { word: "emit", spell: "e-m-i-t", phonetic: "/iˈmɪt/", cn: "发出，排出" },
      { word: "entertaining", spell: "e-n-t-e-r-t-a-i-n-i-n-g", phonetic: "/ˌentəˈteɪnɪŋ/", cn: "有趣的，使人愉快的" },
      { word: "irregular", spell: "i-r-r-e-g-u-l-a-r", phonetic: "/ɪˈreɡjələ/", cn: "不规律的" },
      { word: "psychologist", spell: "p-s-y-c-h-o-l-o-g-i-s-t", phonetic: "/saɪˈkɒlədʒɪst/", cn: "心理学家" },
      { word: "era", spell: "e-r-a", phonetic: "/ˈɪərə/", cn: "纪元，年代" },
      { word: "triumph", spell: "t-r-i-u-m-p-h", phonetic: "/ˈtraɪəmf/", cn: "胜利" },
      { word: "detection", spell: "d-e-t-e-c-t-i-o-n", phonetic: "/dɪˈtekʃn/", cn: "侦查；察觉" }
    ]
  },

  "3s_welcome": {
    title: "三年级上 Welcome unit",
    desc: "入学准备 · 28个",
    words: [
      { word: "let", spell: "l-e-t", phonetic: "/let/", cn: "让" },
      { word: "begin", spell: "b-e-g-i-n", phonetic: "/bɪˈɡɪn/", cn: "开始" },
      { word: "join", spell: "j-o-i-n", phonetic: "/dʒɔɪn/", cn: "加入" },
      { word: "in", spell: "i-n", phonetic: "/ɪn/", cn: "在……中" },
      { word: "English", spell: "E-n-g-l-i-s-h", phonetic: "/ˈɪŋɡlɪʃ/", cn: "英语" },
      { word: "be", spell: "b-e", phonetic: "/biː/", cn: "是" },
      { word: "easy", spell: "e-a-s-y", phonetic: "/ˈiːzi/", cn: "容易的" },
      { word: "come", spell: "c-o-m-e", phonetic: "/kʌm/", cn: "来" },
      { word: "come on", spell: "c-o-m-e o-n", phonetic: "/kʌm ɒn/", cn: "来吧" },
      { word: "and", spell: "a-n-d", phonetic: "/ænd/", cn: "和" },
      { word: "you", spell: "y-o-u", phonetic: "/juː/", cn: "你；你们" },
      { word: "ready", spell: "r-e-a-d-y", phonetic: "/ˈredi/", cn: "准备好的" },
      { word: "kid", spell: "k-i-d", phonetic: "/kɪd/", cn: "小孩，儿童" },
      { word: "yeah", spell: "y-e-a-h", phonetic: "/jeə/", cn: "是" },
      { word: "OK", spell: "O-K", phonetic: "/əʊˈkeɪ/", cn: "行，可以" },
      { word: "listen", spell: "l-i-s-t-e-n", phonetic: "/ˈlɪsn/", cn: "听" },
      { word: "sing", spell: "s-i-n-g", phonetic: "/sɪŋ/", cn: "唱" },
      { word: "speak", spell: "s-p-e-a-k", phonetic: "/spiːk/", cn: "说话" },
      { word: "act", spell: "a-c-t", phonetic: "/ækt/", cn: "表演" },
      { word: "draw", spell: "d-r-a-w", phonetic: "/drɔː/", cn: "画，绘画" },
      { word: "look", spell: "l-o-o-k", phonetic: "/lʊk/", cn: "看" },
      { word: "guess", spell: "g-u-e-s-s", phonetic: "/ɡes/", cn: "猜；猜测" },
      { word: "write", spell: "w-r-i-t-e", phonetic: "/raɪt/", cn: "写" },
      { word: "think", spell: "t-h-i-n-k", phonetic: "/θɪŋk/", cn: "思考" },
      { word: "read", spell: "r-e-a-d", phonetic: "/riːd/", cn: "阅读" },
      { word: "colour", spell: "c-o-l-o-u-r", phonetic: "/ˈkʌlə/", cn: "给……涂上颜色" },
      { word: "play", spell: "p-l-a-y", phonetic: "/pleɪ/", cn: "玩" },
      { word: "hello", spell: "h-e-l-l-o", phonetic: "/həˈləʊ/", cn: "你好" }
    ]
  },

  "3s_1": {
    title: "三年级上 Unit 1",
    desc: "问候与介绍 · 34个",
    words: [
      { word: "what", spell: "w-h-a-t", phonetic: "/wɒt/", cn: "什么" },
      { word: "your", spell: "y-o-u-r", phonetic: "/jɔː/", cn: "你的" },
      { word: "name", spell: "n-a-m-e", phonetic: "/neɪm/", cn: "名字" },
      { word: "I", spell: "I", phonetic: "/aɪ/", cn: "我" },
      { word: "go", spell: "g-o", phonetic: "/ɡəʊ/", cn: "走，去" },
      { word: "we", spell: "w-e", phonetic: "/wiː/", cn: "我们" },
      { word: "all", spell: "a-l-l", phonetic: "/ɔːl/", cn: "每一个" },
      { word: "love", spell: "l-o-v-e", phonetic: "/lʌv/", cn: "喜爱" },
      { word: "a", spell: "a", phonetic: "/eɪ/", cn: "一个" },
      { word: "clever", spell: "c-l-e-v-e-r", phonetic: "/ˈklevə/", cn: "聪明的" },
      { word: "bird", spell: "b-i-r-d", phonetic: "/bɜːd/", cn: "鸟" },
      { word: "him", spell: "h-i-m", phonetic: "/hɪm/", cn: "他" },
      { word: "good", spell: "g-o-o-d", phonetic: "/ɡʊd/", cn: "令人愉快的" },
      { word: "morning", spell: "m-o-r-n-i-n-g", phonetic: "/ˈmɔːnɪŋ/", cn: "早晨，早上" },
      { word: "good morning", spell: "g-o-o-d m-o-r-n-i-n-g", phonetic: "/ɡʊd ˈmɔːnɪŋ/", cn: "早上好" },
      { word: "goodbye", spell: "g-o-o-d-b-y-e", phonetic: "/ɡʊdˈbaɪ/", cn: "再见" },
      { word: "night", spell: "n-i-g-h-t", phonetic: "/naɪt/", cn: "夜晚" },
      { word: "this", spell: "t-h-i-s", phonetic: "/ðɪs/", cn: "这，这个" },
      { word: "nice", spell: "n-i-c-e", phonetic: "/naɪs/", cn: "令人愉快的" },
      { word: "to", spell: "t-o", phonetic: "/tə/", cn: "去；到" },
      { word: "meet", spell: "m-e-e-t", phonetic: "/miːt/", cn: "认识，结识" },
      { word: "happy", spell: "h-a-p-p-y", phonetic: "/ˈhæpi/", cn: "快乐的，高兴的" },
      { word: "birthday", spell: "b-i-r-t-h-d-a-y", phonetic: "/ˈbɜːθdeɪ/", cn: "生日" },
      { word: "happy birthday", spell: "h-a-p-p-y b-i-r-t-h-d-a-y", phonetic: "/ˈhæpi ˈbɜːθdeɪ/", cn: "生日快乐" },
      { word: "afternoon", spell: "a-f-t-e-r-n-o-o-n", phonetic: "/ˌɑːftəˈnuːn/", cn: "下午" },
      { word: "Ms", spell: "M-s", phonetic: "/mɪz/", cn: "女士" },
      { word: "how", spell: "h-o-w", phonetic: "/haʊ/", cn: "如何，怎样" },
      { word: "today", spell: "t-o-d-a-y", phonetic: "/təˈdeɪ/", cn: "今天" },
      { word: "too", spell: "t-o-o", phonetic: "/tuː/", cn: "也" },
      { word: "fine", spell: "f-i-n-e", phonetic: "/faɪn/", cn: "很好" },
      { word: "children", spell: "c-h-i-l-d-r-e-n", phonetic: "/ˈtʃɪldrən/", cn: "儿童，小孩" },
      { word: "cut", spell: "c-u-t", phonetic: "/kʌt/", cn: "剪" },
      { word: "my", spell: "m-y", phonetic: "/maɪ/", cn: "我的" },
      { word: "hi", spell: "h-i", phonetic: "/haɪ/", cn: "你好" }
    ]
  },

  "3s_2": {
    title: "三年级上 Unit 2",
    desc: "颜色与日常 · 37个",
    words: [
      { word: "colourful", spell: "c-o-l-o-u-r-f-u-l", phonetic: "/ˈkʌləfl/", cn: "色彩丰富的" },
      { word: "world", spell: "w-o-r-l-d", phonetic: "/wɜːld/", cn: "世界" },
      { word: "red", spell: "r-e-d", phonetic: "/red/", cn: "红色（的）" },
      { word: "pink", spell: "p-i-n-k", phonetic: "/pɪŋk/", cn: "粉红色（的）" },
      { word: "yellow", spell: "y-e-l-l-o-w", phonetic: "/ˈjeləʊ/", cn: "黄色（的）" },
      { word: "orange", spell: "o-r-a-n-g-e", phonetic: "/ˈɒrɪndʒ/", cn: "橙色（的）" },
      { word: "green", spell: "g-r-e-e-n", phonetic: "/ɡriːn/", cn: "绿色（的）" },
      { word: "brown", spell: "b-r-o-w-n", phonetic: "/braʊn/", cn: "棕色（的）" },
      { word: "black", spell: "b-l-a-c-k", phonetic: "/blæk/", cn: "黑色（的）" },
      { word: "blue", spell: "b-l-u-e", phonetic: "/bluː/", cn: "蓝色（的）" },
      { word: "white", spell: "w-h-i-t-e", phonetic: "/waɪt/", cn: "白色（的）" },
      { word: "purple", spell: "p-u-r-p-l-e", phonetic: "/ˈpɜːpl/", cn: "紫色（的）" },
      { word: "the", spell: "t-h-e", phonetic: "/ðə/", cn: "这，那" },
      { word: "rainbow", spell: "r-a-i-n-b-o-w", phonetic: "/ˈreɪnbəʊ/", cn: "彩虹" },
      { word: "it", spell: "i-t", phonetic: "/ɪt/", cn: "它" },
      { word: "oh", spell: "o-h", phonetic: "/əʊ/", cn: "噢，哦" },
      { word: "start", spell: "s-t-a-r-t", phonetic: "/stɑːt/", cn: "开始" },
      { word: "necklace", spell: "n-e-c-k-l-a-c-e", phonetic: "/ˈnekləs/", cn: "项链" },
      { word: "for", spell: "f-o-r", phonetic: "/fɔː/", cn: "给" },
      { word: "mum", spell: "m-u-m", phonetic: "/mʌm/", cn: "妈妈" },
      { word: "old", spell: "o-l-d", phonetic: "/əʊld/", cn: "旧的" },
      { word: "can", spell: "c-a-n", phonetic: "/kæn/", cn: "能，可以" },
      { word: "paint", spell: "p-a-i-n-t", phonetic: "/peɪnt/", cn: "给……涂颜料" },
      { word: "only", spell: "o-n-l-y", phonetic: "/ˈəʊnli/", cn: "只有，仅" },
      { word: "me", spell: "m-e", phonetic: "/miː/", cn: "我" },
      { word: "thank", spell: "t-h-a-n-k", phonetic: "/θæŋk/", cn: "感谢" },
      { word: "dear", spell: "d-e-a-r", phonetic: "/dɪə/", cn: "亲爱的" },
      { word: "at", spell: "a-t", phonetic: "/æt/", cn: "朝，向" },
      { word: "butterfly", spell: "b-u-t-t-e-r-f-l-y", phonetic: "/ˈbʌtəflaɪ/", cn: "蝴蝶" },
      { word: "lovely", spell: "l-o-v-e-l-y", phonetic: "/ˈlʌvli/", cn: "美丽的；可爱的" },
      { word: "little", spell: "l-i-t-t-l-e", phonetic: "/ˈlɪtl/", cn: "小的" },
      { word: "bye-bye", spell: "b-y-e-b-y-e", phonetic: "/baɪ baɪ/", cn: "再见，拜拜" },
      { word: "favourite", spell: "f-a-v-o-u-r-i-t-e", phonetic: "/ˈfeɪvərɪt/", cn: "最喜欢的" },
      { word: "no", spell: "n-o", phonetic: "/nəʊ/", cn: "不，不是" },
      { word: "yes", spell: "y-e-s", phonetic: "/jes/", cn: "是，对" },
      { word: "that", spell: "t-h-a-t", phonetic: "/ðæt/", cn: "那，那个" },
      { word: "right", spell: "r-i-g-h-t", phonetic: "/raɪt/", cn: "正确的，对的" }
    ]
  },

  "3s_3": {
    title: "三年级上 Unit 3",
    desc: "数字与动物 · 38个",
    words: [
      { word: "number", spell: "n-u-m-b-e-r", phonetic: "/ˈnʌmbə/", cn: "数字" },
      { word: "fun", spell: "f-u-n", phonetic: "/fʌn/", cn: "有趣的" },
      { word: "tiger", spell: "t-i-g-e-r", phonetic: "/ˈtaɪɡə/", cn: "老虎" },
      { word: "jump", spell: "j-u-m-p", phonetic: "/dʒʌmp/", cn: "跳，跃" },
      { word: "do", spell: "d-o", phonetic: "/duː/", cn: "做" },
      { word: "ten", spell: "t-e-n", phonetic: "/ten/", cn: "十" },
      { word: "nine", spell: "n-i-n-e", phonetic: "/naɪn/", cn: "九" },
      { word: "eight", spell: "e-i-g-h-t", phonetic: "/eɪt/", cn: "八" },
      { word: "seven", spell: "s-e-v-e-n", phonetic: "/ˈsevn/", cn: "七" },
      { word: "six", spell: "s-i-x", phonetic: "/sɪks/", cn: "六" },
      { word: "five", spell: "f-i-v-e", phonetic: "/faɪv/", cn: "五" },
      { word: "four", spell: "f-o-u-r", phonetic: "/fɔː/", cn: "四" },
      { word: "three", spell: "t-h-r-e-e", phonetic: "/θriː/", cn: "三" },
      { word: "two", spell: "t-w-o", phonetic: "/tuː/", cn: "二" },
      { word: "one", spell: "o-n-e", phonetic: "/wʌn/", cn: "一" },
      { word: "duck", spell: "d-u-c-k", phonetic: "/dʌk/", cn: "鸭子" },
      { word: "show", spell: "s-h-o-w", phonetic: "/ʃəʊ/", cn: "节目" },
      { word: "about", spell: "a-b-o-u-t", phonetic: "/əˈbaʊt/", cn: "大约" },
      { word: "be about to do sth", spell: "b-e a-b-o-u-t t-o d-o s-t-h", phonetic: "/biː əˈbaʊt tə duː sʌmθɪŋ/", cn: "即将做某事" },
      { word: "dad", spell: "d-a-d", phonetic: "/dæd/", cn: "爸爸" },
      { word: "please", spell: "p-l-e-a-s-e", phonetic: "/pliːz/", cn: "请" },
      { word: "hurry", spell: "h-u-r-r-y", phonetic: "/ˈhʌri/", cn: "赶紧，匆忙" },
      { word: "up", spell: "u-p", phonetic: "/ʌp/", cn: "向上，往上" },
      { word: "hurry up", spell: "h-u-r-r-y u-p", phonetic: "/ˌhʌri ˈʌp/", cn: "快点" },
      { word: "wrong", spell: "w-r-o-n-g", phonetic: "/rɒŋ/", cn: "有问题的" },
      { word: "see", spell: "s-e-e", phonetic: "/siː/", cn: "看见，看到" },
      { word: "many", spell: "m-a-n-y", phonetic: "/ˈmeni/", cn: "许多" },
      { word: "how many", spell: "h-o-w m-a-n-y", phonetic: "/ˌhaʊ ˈmeni/", cn: "多少" },
      { word: "get", spell: "g-e-t", phonetic: "/ɡet/", cn: "移动，去" },
      { word: "out", spell: "o-u-t", phonetic: "/aʊt/", cn: "向外" },
      { word: "get out", spell: "g-e-t o-u-t", phonetic: "/ˌɡet ˈaʊt/", cn: "出去" },
      { word: "have", spell: "h-a-v-e", phonetic: "/hæv/", cn: "进行" },
      { word: "have a look", spell: "h-a-v-e a l-o-o-k", phonetic: "/ˌhæv ə ˈlʊk/", cn: "看一下" },
      { word: "help", spell: "h-e-l-p", phonetic: "/help/", cn: "帮助" },
      { word: "great", spell: "g-r-e-a-t", phonetic: "/ɡreɪt/", cn: "极好的" },
      { word: "late", spell: "l-a-t-e", phonetic: "/leɪt/", cn: "迟到的" },
      { word: "safe", spell: "s-a-f-e", phonetic: "/seɪf/", cn: "安全的" },
      { word: "call", spell: "c-a-l-l", phonetic: "/kɔːl/", cn: "打电话" }
    ]
  },

  "3s_4": {
    title: "三年级上 Unit 4",
    desc: "学习用品 · 22个",
    words: [
      { word: "school", spell: "s-c-h-o-o-l", phonetic: "/skuːl/", cn: "学校" },
      { word: "thing", spell: "t-h-i-n-g", phonetic: "/θɪŋ/", cn: "东西，物" },
      { word: "pencil", spell: "p-e-n-c-i-l", phonetic: "/ˈpensl/", cn: "铅笔" },
      { word: "case", spell: "c-a-s-e", phonetic: "/keɪs/", cn: "盒子" },
      { word: "pencil case", spell: "p-e-n-c-i-l c-a-s-e", phonetic: "/ˈpensl keɪs/", cn: "笔袋；铅笔盒" },
      { word: "pen", spell: "p-e-n", phonetic: "/pen/", cn: "钢笔" },
      { word: "eraser", spell: "e-r-a-s-e-r", phonetic: "/ɪˈreɪzə/", cn: "橡皮" },
      { word: "schoolbag", spell: "s-c-h-o-o-l-b-a-g", phonetic: "/ˈskuːlbæɡ/", cn: "书包" },
      { word: "ruler", spell: "r-u-l-e-r", phonetic: "/ˈruːlə/", cn: "尺子，直尺" },
      { word: "book", spell: "b-o-o-k", phonetic: "/bʊk/", cn: "书籍" },
      { word: "home", spell: "h-o-m-e", phonetic: "/həʊm/", cn: "到家，回家" },
      { word: "where", spell: "w-h-e-r-e", phonetic: "/weə/", cn: "在哪里" },
      { word: "picture", spell: "p-i-c-t-u-r-e", phonetic: "/ˈpɪktʃə/", cn: "图画" },
      { word: "on", spell: "o-n", phonetic: "/ɒn/", cn: "在……上面" },
      { word: "wall", spell: "w-a-l-l", phonetic: "/wɔːl/", cn: "墙" },
      { word: "paper", spell: "p-a-p-e-r", phonetic: "/ˈpeɪpə/", cn: "纸" },
      { word: "open", spell: "o-p-e-n", phonetic: "/ˈəʊpən/", cn: "打开" },
      { word: "take", spell: "t-a-k-e", phonetic: "/teɪk/", cn: "拿" },
      { word: "take out", spell: "t-a-k-e o-u-t", phonetic: "/ˌteɪk ˈaʊt/", cn: "拿出" },
      { word: "rope", spell: "r-o-p-e", phonetic: "/rəʊp/", cn: "绳索" },
      { word: "skipping rope", spell: "s-k-i-p-p-i-n-g r-o-p-e", phonetic: "/ˈskɪpɪŋ rəʊp/", cn: "跳绳" }
    ]
  },

  "3s_5": {
    title: "三年级上 Unit 5",
    desc: "教室场景 · 27个",
    words: [
      { word: "classroom", spell: "c-l-a-s-s-r-o-o-m", phonetic: "/ˈklɑːsruːm/", cn: "教室" },
      { word: "blackboard", spell: "b-l-a-c-k-b-o-a-r-d", phonetic: "/ˈblækbɔːd/", cn: "黑板" },
      { word: "door", spell: "d-o-o-r", phonetic: "/dɔː/", cn: "门" },
      { word: "window", spell: "w-i-n-d-o-w", phonetic: "/ˈwɪndəʊ/", cn: "窗户" },
      { word: "desk", spell: "d-e-s-k", phonetic: "/desk/", cn: "书桌" },
      { word: "chair", spell: "c-h-a-i-r", phonetic: "/tʃeə/", cn: "椅子" },
      { word: "floor", spell: "f-l-o-o-r", phonetic: "/flɔː/", cn: "地面" },
      { word: "ball", spell: "b-a-l-l", phonetic: "/bɔːl/", cn: "球" },
      { word: "behind", spell: "b-e-h-i-n-d", phonetic: "/bɪˈhaɪnd/", cn: "在……后面" },
      { word: "front", spell: "f-r-o-n-t", phonetic: "/frʌnt/", cn: "前面" },
      { word: "of", spell: "o-f", phonetic: "/ɒv/", cn: "……的" },
      { word: "in front of", spell: "i-n f-r-o-n-t o-f", phonetic: "/ɪn frʌnt ɒv/", cn: "在……前面" },
      { word: "beside", spell: "b-e-s-i-d-e", phonetic: "/bɪˈsaɪd/", cn: "在……旁边" },
      { word: "under", spell: "u-n-d-e-r", phonetic: "/ˈʌndə/", cn: "在……下面" },
      { word: "now", spell: "n-o-w", phonetic: "/naʊ/", cn: "现在" },
      { word: "class", spell: "c-l-a-s-s", phonetic: "/klɑːs/", cn: "班，班级" },
      { word: "wow", spell: "w-o-w", phonetic: "/waʊ/", cn: "哇，呀" },
      { word: "next", spell: "n-e-x-t", phonetic: "/nekst/", cn: "紧接下来" },
      { word: "keep", spell: "k-e-e-p", phonetic: "/kiːp/", cn: "饲养" },
      { word: "with", spell: "w-i-t-h", phonetic: "/wɪð/", cn: "和……一起" },
      { word: "over", spell: "o-v-e-r", phonetic: "/ˈəʊvə/", cn: "结束" },
      { word: "clean", spell: "c-l-e-a-n", phonetic: "/kliːn/", cn: "使清洁，清理" },
      { word: "sweep", spell: "s-w-e-e-p", phonetic: "/swiːp/", cn: "打扫，清扫" },
      { word: "put", spell: "p-u-t", phonetic: "/pʊt/", cn: "放，放置" },
      { word: "tomorrow", spell: "t-o-m-o-r-r-o-w", phonetic: "/təˈmɒrəʊ/", cn: "明天" },
      { word: "they", spell: "t-h-e-y", phonetic: "/ðeɪ/", cn: "他们；她们；它们" }
    ]
  },

  "3s_6": {
    title: "三年级上 Unit 6",
    desc: "家庭与日常 · 32个",
    words: [
      { word: "family", spell: "f-a-m-i-l-y", phonetic: "/ˈfæməli/", cn: "家，家庭" },
      { word: "brother", spell: "b-r-o-t-h-e-r", phonetic: "/ˈbrʌðə/", cn: "哥哥；弟弟" },
      { word: "sister", spell: "s-i-s-t-e-r", phonetic: "/ˈsɪstə/", cn: "姐姐；妹妹" },
      { word: "grandpa", spell: "g-r-a-n-d-p-a", phonetic: "/ˈɡrænpɑː/", cn: "爷爷；外公" },
      { word: "grandma", spell: "g-r-a-n-d-m-a", phonetic: "/ˈɡrænmɑː/", cn: "奶奶；外婆" },
      { word: "some", spell: "s-o-m-e", phonetic: "/sʌm/", cn: "一些" },
      { word: "tea", spell: "t-e-a", phonetic: "/tiː/", cn: "茶" },
      { word: "uncle", spell: "u-n-c-l-e", phonetic: "/ˈʌŋkl/", cn: "叔叔；伯伯；舅舅" },
      { word: "aunt", spell: "a-u-n-t", phonetic: "/ɑːnt/", cn: "阿姨；姑妈；伯母" },
      { word: "long", spell: "l-o-n-g", phonetic: "/lɒŋ/", cn: "长时间的" },
      { word: "time", spell: "t-i-m-e", phonetic: "/taɪm/", cn: "时间" },
      { word: "sport", spell: "s-p-o-r-t", phonetic: "/spɔːt/", cn: "体育运动" },
      { word: "day", spell: "d-a-y", phonetic: "/deɪ/", cn: "一天" },
      { word: "sports day", spell: "s-p-o-r-t-s d-a-y", phonetic: "/ˈspɔːts deɪ/", cn: "运动日" },
      { word: "their", spell: "t-h-e-i-r", phonetic: "/ðeə/", cn: "他们的" },
      { word: "dog", spell: "d-o-g", phonetic: "/dɒɡ/", cn: "狗" },
      { word: "win", spell: "w-i-n", phonetic: "/wɪn/", cn: "获胜，赢" },
      { word: "best", spell: "b-e-s-t", phonetic: "/best/", cn: "最好的" },
      { word: "job", spell: "j-o-b", phonetic: "/dʒɒb/", cn: "工作，任务" },
      { word: "good job", spell: "g-o-o-d j-o-b", phonetic: "/ˌɡʊd ˈdʒɒb/", cn: "干得好，真不错" },
      { word: "all right", spell: "a-l-l r-i-g-h-t", phonetic: "/ˌɔːl ˈraɪt/", cn: "没有问题的" },
      { word: "well", spell: "w-e-l-l", phonetic: "/wel/", cn: "令人满意地" },
      { word: "well done", spell: "w-e-l-l d-o-n-e", phonetic: "/ˌwel ˈdʌn/", cn: "干得好，真棒" },
      { word: "he", spell: "h-e", phonetic: "/hiː/", cn: "他" },
      { word: "she", spell: "s-h-e", phonetic: "/ʃiː/", cn: "她" },
      { word: "grandfather", spell: "g-r-a-n-d-f-a-t-h-e-r", phonetic: "/ˈɡrænfɑːðə/", cn: "祖父；外祖父" },
      { word: "mother", spell: "m-o-t-h-e-r", phonetic: "/ˈmʌðə/", cn: "母亲" },
      { word: "grandmother", spell: "g-r-a-n-d-m-o-t-h-e-r", phonetic: "/ˈɡrænmʌðə/", cn: "祖母；外祖母" },
      { word: "father", spell: "f-a-t-h-e-r", phonetic: "/ˈfɑːðə/", cn: "父亲" },
      { word: "who", spell: "w-h-o", phonetic: "/huː/", cn: "谁" },
      { word: "cousin", spell: "c-o-u-s-i-n", phonetic: "/ˈkʌzn/", cn: "堂（表）兄弟；姐妹" },
      { word: "her", spell: "h-e-r", phonetic: "/hɜː/", cn: "她的" }
    ]
  },

  "3s_7": {
    title: "三年级上 Plays & 生活",
    desc: "故事与自然 · 43个",
    words: [
      { word: "magic", spell: "m-a-g-i-c", phonetic: "/ˈmædʒɪk/", cn: "神奇的" },
      { word: "paintbrush", spell: "p-a-i-n-t-b-r-u-s-h", phonetic: "/ˈpeɪntbrʌʃ/", cn: "画笔" },
      { word: "like", spell: "l-i-k-e", phonetic: "/laɪk/", cn: "喜欢" },
      { word: "man", spell: "m-a-n", phonetic: "/mæn/", cn: "人" },
      { word: "boy", spell: "b-o-y", phonetic: "/bɔɪ/", cn: "男孩" },
      { word: "here", spell: "h-e-r-e", phonetic: "/hɪə/", cn: "在这里" },
      { word: "here you are", spell: "h-e-r-e y-o-u a-r-e", phonetic: "/hɪə juː ɑː/", cn: "给你" },
      { word: "fly", spell: "f-l-y", phonetic: "/flaɪ/", cn: "飞翔" },
      { word: "run", spell: "r-u-n", phonetic: "/rʌn/", cn: "奔跑" },
      { word: "girl", spell: "g-i-r-l", phonetic: "/ɡɜːl/", cn: "女孩" },
      { word: "hear", spell: "h-e-a-r", phonetic: "/hɪə/", cn: "得知" },
      { word: "hungry", spell: "h-u-n-g-r-y", phonetic: "/ˈhʌŋɡri/", cn: "饥饿的" },
      { word: "noodle", spell: "n-o-o-d-l-e", phonetic: "/ˈnuːdl/", cn: "面条" },
      { word: "cold", spell: "c-o-l-d", phonetic: "/kəʊld/", cn: "冷的，寒冷的" },
      { word: "coat", spell: "c-o-a-t", phonetic: "/kəʊt/", cn: "大衣，外套" },
      { word: "emperor", spell: "e-m-p-e-r-o-r", phonetic: "/ˈempərə/", cn: "皇帝" },
      { word: "want", spell: "w-a-n-t", phonetic: "/wɒnt/", cn: "想要" },
      { word: "money", spell: "m-o-n-e-y", phonetic: "/ˈmʌni/", cn: "钱" },
      { word: "tree", spell: "t-r-e-e", phonetic: "/triː/", cn: "树木" },
      { word: "island", spell: "i-s-l-a-n-d", phonetic: "/ˈaɪlənd/", cn: "岛屿" },
      { word: "sea", spell: "s-e-a", phonetic: "/siː/", cn: "海洋" },
      { word: "ship", spell: "s-h-i-p", phonetic: "/ʃɪp/", cn: "大船" },
      { word: "wind", spell: "w-i-n-d", phonetic: "/wɪnd/", cn: "风" },
      { word: "more", spell: "m-o-r-e", phonetic: "/mɔː/", cn: "更多的" },
      { word: "fall", spell: "f-a-l-l", phonetic: "/fɔːl/", cn: "跌落" },
      { word: "into", spell: "i-n-t-o", phonetic: "/ˈɪntə/", cn: "到……里面" },
      { word: "after", spell: "a-f-t-e-r", phonetic: "/ˈɑːftə/", cn: "在……后" },
      { word: "use", spell: "u-s-e", phonetic: "/juːz/", cn: "用，使用" },
      { word: "his", spell: "h-i-s", phonetic: "/hɪz/", cn: "他的" },
      { word: "give", spell: "g-i-v-e", phonetic: "/ɡɪv/", cn: "递给" },
      { word: "pear", spell: "p-e-a-r", phonetic: "/peə/", cn: "梨" },
      { word: "year", spell: "y-e-a-r", phonetic: "/jɪə/", cn: "岁" },
      { word: "big", spell: "b-i-g", phonetic: "/bɪɡ/", cn: "大的" },
      { word: "welcome", spell: "w-e-l-c-o-m-e", phonetic: "/ˈwelkəm/", cn: "欢迎" },
      { word: "juicy", spell: "j-u-i-c-y", phonetic: "/ˈdʒuːsi/", cn: "多汁的" },
      { word: "sweet", spell: "s-w-e-e-t", phonetic: "/swiːt/", cn: "甜的" },
      { word: "beautiful", spell: "b-e-a-u-t-i-f-u-l", phonetic: "/ˈbjuːtɪfl/", cn: "美丽的；极好的" },
      { word: "small", spell: "s-m-a-l-l", phonetic: "/smɔːl/", cn: "小的" },
      { word: "eat", spell: "e-a-t", phonetic: "/iːt/", cn: "吃" },
      { word: "very", spell: "v-e-r-y", phonetic: "/ˈveri/", cn: "很，非常" },
      { word: "kind", spell: "k-i-n-d", phonetic: "/kaɪnd/", cn: "体贴的；和蔼的" }
    ]
  }
};
